mutation {
  addToCart(
    userId: "b2db7761-fb9d-4e0c-85df-5bd64446a484"
    productId: "66VCHSJNUP"
    quantity: 1
  ) {
    userId
    items {
      productId
      quantity
    }
  }
}

mutation {
  addToCart(
    userId: "b2db7761-fb9d-4e0c-85df-5bd64446a484"
    productId: "LS4PSXUNUM"
    quantity: 2
  ) {
    userId
    items {
      productId
      quantity
    }
  }
}

Response:
{
  "data": {
    "addToCart": {
      "userId": "b2db7761-fb9d-4e0c-85df-5bd64446a484",
      "items": [
        {
          "productId": "66VCHSJNUP",
          "quantity": 1
        },
        {
          "productId": "LS4PSXUNUM",
          "quantity": 2
        }
      ]
    }
  }
}


query {
    cart(sessionId: "b2db7761-fb9d-4e0c-85df-5bd64446a484", currencyCode: "USD") {
        userId
        items {
            productId
            quantity
            }
            }
    recommendations(
        sessionId: "b2db7761-fb9d-4e0c-85df-5bd64446a484"
        currencyCode: "USD"
        ) {
            id
            name
            price
            }
}

Response:
{
  "data": {
    "cart": {
      "userId": "b2db7761-fb9d-4e0c-85df-5bd64446a484",
      "items": [
        {
          "productId": "66VCHSJNUP",
          "quantity": 1
        },
        {
          "productId": "LS4PSXUNUM",
          "quantity": 2
        }
      ]
    },
    "recommendations": [
      {
        "id": "OLJCESPC7Z",
        "name": "National Park Foundation Explorascope",
        "price": 101.96
      },
      {
        "id": "L9ECAV7KIM",
        "name": "Lens Cleaning Kit",
        "price": 21.95
      },
      {
        "id": "66VCHSJNUP",
        "name": "Starsense Explorer Refractor Telescope",
        "price": 349.95
      },
      {
        "id": "2ZYFJ3GM2N",
        "name": "Roof Binoculars",
        "price": 209.95
      }
    ]
  }
}