mutation {
  addToCart(
    userId: "b2db7761-fb9d-4e0c-85df-5bd64446a484"
    productId: "66VCHSJNUP"
    quantity: 1
  ) {
    userId
    items {
      productId
      quantity
    }
  }
}

query {
  cart(sessionId: "b2db7761-fb9d-4e0c-85df-5bd64446a484", currencyCode: "USD") {
    userId
    items {
      productId
      quantity
    }
  }
}

Response:
{
  "data": {
    "cart": {
      "userId": "b2db7761-fb9d-4e0c-85df-5bd64446a484",
      "items": [
        {
          "productId": "66VCHSJNUP",
          "quantity": 1
        }
      ]
    }
  }
}